# Generated by Django 4.2.3 on 2023-08-08 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Afiliados', '0002_rename_cartorio_afiliadosmodel_bairro_and_more'),
        ('Servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('RegistroGeral', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=11)),
                ('estado_civil', models.CharField(blank=True, choices=[('S', 'Solteiro'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viúvo')], max_length=1, null=True)),
                ('profissao', models.CharField(blank=True, max_length=100, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('endereco', models.TextField()),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=9)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Analise'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=50)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('afiliado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Afiliados.afiliadosmodel')),
                ('subservico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NovoCliente', to='Servicos.subservico')),
            ],
        ),
        migrations.CreateModel(
            name='NovoClienteEnvolvido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('sobrenome', models.CharField(blank=True, max_length=100, null=True)),
                ('RegistroGeral', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Pedidos.novocliente')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('descricao', models.CharField(max_length=255)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedidos.novocliente')),
            ],
        ),
    ]
