# Generated by Django 4.2.3 on 2023-08-26 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NovoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('RegistroGeral', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=11)),
                ('estado_civil', models.CharField(blank=True, choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viuvo', 'Viúvo')], max_length=15, null=True)),
                ('profissao', models.CharField(blank=True, max_length=100, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('endereco', models.TextField()),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=9)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Analise'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=50)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('servico', models.CharField(blank=True, max_length=100, null=True)),
                ('subservico', models.CharField(blank=True, max_length=100, null=True)),
                ('nomeEnvolvido', models.CharField(blank=True, max_length=100, null=True)),
                ('sobrenomeEnvolvido', models.CharField(blank=True, max_length=100, null=True)),
                ('RegistroGeralEnvolvido', models.CharField(blank=True, max_length=20, null=True)),
                ('cpfEnvolvido', models.CharField(blank=True, max_length=11, null=True)),
                ('nomeCartorio', models.CharField(blank=True, max_length=100, null=True)),
                ('estadoCartorio', models.CharField(blank=True, max_length=100, null=True)),
                ('livroCartorio', models.CharField(blank=True, max_length=100, null=True)),
                ('folhaCartorio', models.CharField(blank=True, max_length=100, null=True)),
                ('nomeCartorioFirmaReconhecida', models.CharField(blank=True, max_length=100, null=True)),
                ('estadoCartorioFirmaReconhecida', models.CharField(blank=True, max_length=100, null=True)),
                ('livroCartorioFirmaReconhecida', models.CharField(blank=True, max_length=100, null=True)),
                ('afiliado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pedidos.novocliente')),
            ],
        ),
    ]
