# Generated by Django 4.2.3 on 2023-08-09 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servicos', '0001_initial'),
        ('Pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novocliente',
            name='subservico',
        ),
        migrations.AddField(
            model_name='novocliente',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NovoCliente', to='Servicos.servico'),
        ),
    ]
