# Generated by Django 4.2.3 on 2023-09-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novocliente',
            name='idCliente',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
