# Generated by Django 4.2.3 on 2023-09-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0002_novocliente_idcliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='novocliente',
            name='Observacoes',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
