# Generated by Django 4.2.3 on 2023-09-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0004_alter_novocliente_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novocliente',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em analise', 'Em Analise'), ('Aprovado', 'Aprovado'), ('Recusado', 'Recusado'), ('Ajustar documentaçãoo', 'Ajustar documentação')], default='pendente', max_length=50),
        ),
    ]
