# Generated by Django 4.2.3 on 2023-09-29 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servicos', '0005_remove_servico_nome_categoria'),
        ('Pedidos', '0007_alter_novocliente_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='novocliente',
            name='servicoCadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Servicos.servico'),
        ),
    ]
