# Generated by Django 4.2.3 on 2023-09-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0008_novocliente_servicocadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='novocliente',
            name='filiacao1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='novocliente',
            name='filiacao2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
