# Generated by Django 4.2.3 on 2023-09-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0009_novocliente_filiacao1_novocliente_filiacao2'),
    ]

    operations = [
        migrations.AddField(
            model_name='novocliente',
            name='termo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
