# Generated by Django 4.2.3 on 2023-10-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0011_novocliente_cidadecartorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='novocliente',
            name='tipoDeEntrega',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
