# Generated by Django 4.2.3 on 2023-10-01 13:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
        ('Servicos', '0007_delete_subservico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pedidos', '0014_remove_novocliente_sobrenome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NovoCliente',
            new_name='Processos',
        ),
    ]
