# Generated by Django 4.2.3 on 2023-10-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0015_rename_novocliente_processos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='idCliente',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
