# Generated by Django 4.2.3 on 2023-10-02 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servicos', '0007_delete_subservico'),
        ('Pedidos', '0017_remove_processos_servicocadastro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processos',
            name='servicoCadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Servicos.servico'),
        ),
        migrations.AlterField(
            model_name='processos',
            name='servico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
