# Generated by Django 4.2.3 on 2023-10-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0018_processos_servicocadastro_alter_processos_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='processos',
            name='FormaDePagamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
