# Generated by Django 4.2.3 on 2023-10-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0019_processos_formadepagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='processos',
            name='conjugue1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processos',
            name='conjugue2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
