# Generated by Django 4.2.3 on 2023-10-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0022_processos_data_obito'),
    ]

    operations = [
        migrations.AddField(
            model_name='processos',
            name='nome_falecido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
