# Generated by Django 4.2.3 on 2023-10-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0023_processos_nome_falecido'),
    ]

    operations = [
        migrations.AddField(
            model_name='processos',
            name='data_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processos',
            name='data_inicial',
            field=models.DateField(blank=True, null=True),
        ),
    ]
