# Generated by Django 4.2.3 on 2023-11-12 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pedidos', '0025_processos_filhoincapaz_processos_tembens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processos',
            name='funcionario',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'FUNC'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_funcionario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='processos',
            name='afiliado',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'AFILIADO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_afiliado', to=settings.AUTH_USER_MODEL),
        ),
    ]
