# Generated by Django 4.2.3 on 2023-12-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0029_processos_status_adm_afiliado'),
    ]

    operations = [
        migrations.AddField(
            model_name='processos',
            name='bairro_envolvido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processos',
            name='cep_envolvido',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='processos',
            name='cidade_envolvido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processos',
            name='endereco_envolvido',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processos',
            name='estado_envolvido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
