# Generated by Django 4.2.3 on 2023-12-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0031_rename_endereco_processos_complemento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processos',
            name='emailEnvolvido',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
