# Generated by Django 4.2.3 on 2023-12-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0032_processos_emailenvolvido'),
    ]

    operations = [
        migrations.AddField(
            model_name='processos',
            name='telefoneEnvolvido',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
