# Generated by Django 4.2.3 on 2023-12-08 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0034_financiamentoveiculo_clientjob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientjob',
            old_name='cliente',
            new_name='processo',
        ),
        migrations.RenameField(
            model_name='financiamentoveiculo',
            old_name='cliente',
            new_name='processo',
        ),
    ]
