# Generated by Django 4.2.3 on 2023-12-08 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0035_rename_cliente_clientjob_processo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientjob',
            name='processo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pedidos.processos'),
        ),
        migrations.AlterField(
            model_name='financiamentoveiculo',
            name='processo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pedidos.processos'),
        ),
    ]
