# Generated by Django 4.2.3 on 2023-12-08 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0036_alter_clientjob_processo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientEmpresarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(blank=True, max_length=100, null=True)),
                ('razao_social', models.CharField(blank=True, max_length=100, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=100, null=True)),
                ('data_abertura', models.DateField(blank=True, null=True)),
                ('faturamento_mensal', models.CharField(blank=True, max_length=100, null=True)),
                ('contador_nome', models.CharField(blank=True, max_length=9, null=True)),
                ('telefone_contador', models.TextField(blank=True, null=True)),
                ('processo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pedidos.processos')),
            ],
        ),
    ]
