# Generated by Django 4.2.3 on 2023-12-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0037_clientempresarial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financiamentoveiculo',
            old_name='ano',
            new_name='ano_fabricacao',
        ),
        migrations.AddField(
            model_name='financiamentoveiculo',
            name='ano_modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financiamentoveiculo',
            name='cambio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financiamentoveiculo',
            name='combustivel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financiamentoveiculo',
            name='possui_carroceria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
