# Generated by Django 4.2.3 on 2023-12-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0040_remove_processos_bairro_remove_processos_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processos',
            name='cnh',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='processos',
            name='genero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='processos',
            name='naturalidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
