# Generated by Django 4.2.3 on 2023-12-09 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0041_processos_cnh_processos_genero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processos',
            name='Data_emissao_rg',
        ),
        migrations.RemoveField(
            model_name='processos',
            name='RegistroGeral',
        ),
        migrations.RemoveField(
            model_name='processos',
            name='cnh',
        ),
        migrations.RemoveField(
            model_name='processos',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='processos',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='processos',
            name='email',
        ),
        migrations.RemoveField(
            model_name='processos',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='processos',
            name='filiacao1',
        ),
        migrations.RemoveField(
            model_name='processos',
            name='filiacao2',
        ),
        migrations.RemoveField(
            model_name='processos',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='processos',
            name='naturalidade',
        ),
        migrations.RemoveField(
            model_name='processos',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='processos',
            name='orgao_emissor_rg',
        ),
        migrations.RemoveField(
            model_name='processos',
            name='profissao',
        ),
        migrations.RemoveField(
            model_name='processos',
            name='telefone',
        ),
    ]
