# Generated by Django 4.2.3 on 2023-12-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0042_remove_processos_data_emissao_rg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processos',
            name='filiacao1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processos',
            name='filiacao2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
