# Generated by Django 4.2.3 on 2023-12-10 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0045_remove_financiamentoveiculo_nome_referencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteTerceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEnvolvido', models.CharField(blank=True, max_length=100, null=True)),
                ('sobrenomeEnvolvido', models.CharField(blank=True, max_length=100, null=True)),
                ('RegistroGeralEnvolvido', models.CharField(blank=True, max_length=20, null=True)),
                ('cpfEnvolvido', models.CharField(blank=True, max_length=11, null=True)),
                ('emailEnvolvido', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefoneEnvolvido', models.CharField(blank=True, max_length=15, null=True)),
                ('estado_envolvido', models.CharField(blank=True, max_length=50, null=True)),
                ('logradouro_envolvido', models.TextField(blank=True, null=True)),
                ('complemento_envolvido', models.TextField(blank=True, null=True)),
                ('cidade_envolvido', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro_envolvido', models.CharField(blank=True, max_length=100, null=True)),
                ('cep_envolvido', models.CharField(blank=True, max_length=9, null=True)),
                ('numero_envolvido', models.CharField(blank=True, max_length=9, null=True)),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pedidos.processos')),
            ],
        ),
        migrations.CreateModel(
            name='Cartorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCartorio', models.CharField(blank=True, max_length=100, null=True)),
                ('estadoCartorio', models.CharField(blank=True, max_length=100, null=True)),
                ('cidadeCartorio', models.CharField(blank=True, max_length=100, null=True)),
                ('livroCartorio', models.CharField(blank=True, max_length=100, null=True)),
                ('folhaCartorio', models.CharField(blank=True, max_length=100, null=True)),
                ('termo', models.CharField(blank=True, max_length=100, null=True)),
                ('nomeCartorioFirmaReconhecida', models.CharField(blank=True, max_length=100, null=True)),
                ('estadoCartorioFirmaReconhecida', models.CharField(blank=True, max_length=100, null=True)),
                ('livroCartorioFirmaReconhecida', models.CharField(blank=True, max_length=100, null=True)),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pedidos.processos')),
            ],
        ),
    ]
