# Generated by Django 4.2.3 on 2023-12-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0047_processos_fisico_juridico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientempresarial',
            name='contador_nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientempresarial',
            name='telefone_contador',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
    ]
