# Generated by Django 4.2.3 on 2023-12-10 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0048_alter_clientempresarial_contador_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certidoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(blank=True, max_length=100, null=True)),
                ('filiacao1', models.CharField(blank=True, max_length=100, null=True)),
                ('filiacao2', models.CharField(blank=True, max_length=100, null=True)),
                ('conjugue1', models.CharField(blank=True, max_length=100, null=True)),
                ('conjugue2', models.CharField(blank=True, max_length=100, null=True)),
                ('data_casamento', models.DateField(blank=True, null=True)),
                ('data_inicial', models.DateField(blank=True, null=True)),
                ('data_final', models.DateField(blank=True, null=True)),
                ('data_obito', models.DateField(blank=True, null=True)),
                ('nome_falecido', models.CharField(blank=True, max_length=100, null=True)),
                ('temFilhosMenores', models.CharField(blank=True, max_length=5, null=True)),
                ('temBens', models.CharField(blank=True, max_length=5, null=True)),
                ('filhoIncapaz', models.CharField(blank=True, max_length=5, null=True)),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pedidos.processos')),
            ],
        ),
    ]
