# Generated by Django 4.2.3 on 2023-12-11 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0016_remove_cliente_filiacao1_remove_cliente_filiacao2'),
        ('Pedidos', '0050_remove_processos_registrogeralenvolvido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processos',
            name='idCliente',
        ),
        migrations.AddField(
            model_name='processos',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='Cliente.cliente'),
            preserve_default=False,
        ),
    ]
