# Generated by Django 4.2.3 on 2023-12-11 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0016_remove_cliente_filiacao1_remove_cliente_filiacao2'),
        ('Pedidos', '0051_remove_processos_idcliente_processos_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='Cliente.cliente'),
        ),
    ]
