# Generated by Django 4.2.3 on 2023-12-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0054_alter_processos_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='processos',
            name='idCliente',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
