# Generated by Django 4.2.3 on 2023-12-11 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0055_processos_idcliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processos',
            name='idCliente',
        ),
    ]
