# Generated by Django 4.2.3 on 2023-12-11 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0057_alter_processos_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanciamentoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_imovel', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_imovel', models.CharField(blank=True, max_length=100, null=True)),
                ('situacao_imovel', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_imovel', models.CharField(blank=True, max_length=100, null=True)),
                ('compor_renda', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_financiamento', models.CharField(blank=True, max_length=100, null=True)),
                ('quantas_parcelas', models.CharField(blank=True, max_length=100, null=True)),
                ('despesas_extra', models.CharField(blank=True, max_length=100, null=True)),
                ('amortizacao', models.CharField(blank=True, max_length=100, null=True)),
                ('agencia', models.CharField(blank=True, max_length=100, null=True)),
                ('conta', models.CharField(blank=True, max_length=100, null=True)),
                ('utilizara_fgts', models.CharField(blank=True, max_length=100, null=True)),
                ('possui_dependentes', models.CharField(blank=True, max_length=100, null=True)),
                ('recebe_qual_banco', models.CharField(blank=True, max_length=100, null=True)),
                ('recepcao_documentos', models.CharField(blank=True, choices=[('Pendente de Envio de Documentação', 'Pendente de Envio de Documentação'), ('Em análise', 'Em análise'), ('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], max_length=100, null=True)),
                ('analise_de_documentos', models.CharField(blank=True, choices=[('Pendente de Envio de Documentação', 'Pendente de Envio de Documentação'), ('Em análise', 'Em análise'), ('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], max_length=100, null=True)),
                ('analise_de_redito', models.CharField(blank=True, choices=[('Pendente de Envio de Documentação', 'Pendente de Envio de Documentação'), ('Em análise', 'Em análise'), ('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], max_length=100, null=True)),
                ('avaliacao_do_imovel', models.CharField(blank=True, choices=[('Pendente de Envio de Documentação', 'Pendente de Envio de Documentação'), ('Em análise', 'Em análise'), ('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], max_length=100, null=True)),
                ('analise_juridica', models.CharField(blank=True, choices=[('Pendente de Envio de Documentação', 'Pendente de Envio de Documentação'), ('Em análise', 'Em análise'), ('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], max_length=100, null=True)),
                ('registro_de_contrato', models.CharField(blank=True, choices=[('Pendente de Envio de Documentação', 'Pendente de Envio de Documentação'), ('Em análise', 'Em análise'), ('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], max_length=100, null=True)),
                ('possui_produtos_ativos', models.BooleanField(blank=True, default=False, null=True)),
                ('detalhes_produtos_ativos', models.TextField(blank=True, null=True)),
                ('detalhes_instituicao_financeira', models.TextField(blank=True, null=True)),
                ('valores_aproximados_despesas', models.TextField(blank=True, null=True)),
                ('processo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pedidos.processos')),
            ],
        ),
    ]
