# Generated by Django 4.2.3 on 2023-12-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0058_financiamentoimovel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financiamentoimovel',
            name='detalhes_instituicao_financeira',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financiamentoimovel',
            name='detalhes_produtos_ativos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financiamentoimovel',
            name='valores_aproximados_despesas',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
