# Generated by Django 4.2.3 on 2023-12-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0059_alter_financiamentoimovel_detalhes_instituicao_financeira_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financiamentoimovel',
            name='possui_produtos_ativos',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
