# Generated by Django 4.2.3 on 2023-12-11 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0060_alter_financiamentoimovel_possui_produtos_ativos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financiamentoimovel',
            old_name='analise_de_redito',
            new_name='analise_de_credito',
        ),
    ]
