# Generated by Django 4.2.3 on 2023-12-13 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0061_rename_analise_de_redito_financiamentoimovel_analise_de_credito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financiamentoimovel',
            name='detalhes_instituicao_financeira',
        ),
    ]
