# Generated by Django 4.2.3 on 2023-12-14 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0063_remove_financiamentoimovel_valores_aproximados_despesas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financiamentoimovel',
            name='detalhes_produtos_ativos',
        ),
    ]
