# Generated by Django 4.2.3 on 2023-12-15 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pedidos', '0065_remove_financiamentoimovel_detalhes_produtos_ativos_data_ultimo_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='cliente',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'CLIENTE'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processos', to=settings.AUTH_USER_MODEL),
        ),
    ]
