# Generated by Django 4.2.3 on 2023-12-20 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servicos', '0007_delete_subservico'),
        ('Pedidos', '0066_alter_processos_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaServicosGeralVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa_veiculo', models.CharField(blank=True, max_length=11, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=100, null=True)),
                ('servicoCadastro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Servicos.servico')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultaServicosGeralCPF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=100, null=True)),
                ('servicoCadastro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Servicos.servico')),
            ],
        ),
    ]
