# Generated by Django 4.2.3 on 2023-12-26 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0068_consultaservicosgeralcpf_nome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultaservicosgeralveiculo',
            old_name='servicoCadastro',
            new_name='servico',
        ),
    ]
