# Generated by Django 4.2.3 on 2023-12-26 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0069_rename_servicocadastro_consultaservicosgeralveiculo_servico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultaservicosgeralcpf',
            old_name='servicoCadastro',
            new_name='servico',
        ),
    ]
