# Generated by Django 4.2.3 on 2023-12-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0073_alter_consultaservicosgeralcpf_processo'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultaservicosgeralcpf',
            name='subservico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
