# Generated by Django 4.2.3 on 2023-12-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0074_consultaservicosgeralcpf_subservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultaservicosgeralveiculo',
            name='subservico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
