# Generated by Django 4.2.3 on 2023-12-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0075_consultaservicosgeralveiculo_subservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultaservicosgeralcpf',
            name='placa_veiculo',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
