# Generated by Django 4.2.3 on 2023-12-26 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0076_consultaservicosgeralcpf_placa_veiculo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsultaServicosGeralVeiculo',
        ),
    ]
