# Generated by Django 4.2.3 on 2023-12-26 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servicos', '0007_delete_subservico'),
        ('Pedidos', '0077_delete_consultaservicosgeralveiculo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsultaServicosGeralCPF',
            new_name='ConsultaServicosGeral',
        ),
    ]
