# Generated by Django 4.2.3 on 2023-12-26 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servicos', '0007_delete_subservico'),
        ('Pedidos', '0078_rename_consultaservicosgeralcpf_consultaservicosgeral'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmprestimosEmGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subservico', models.CharField(blank=True, max_length=100, null=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('telefone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('numero_beneficio', models.CharField(blank=True, max_length=100, null=True)),
                ('agencia', models.CharField(blank=True, max_length=100, null=True)),
                ('conta', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_conta', models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Conjunta', 'Conjunta'), ('Corrente', 'Corrente'), ('Poupança', 'Poupança')], max_length=100, null=True)),
                ('possui_representante_legal', models.CharField(blank=True, max_length=5, null=True)),
                ('alfaetizado', models.CharField(blank=True, max_length=5, null=True)),
                ('finalidade_emprestimo', models.CharField(blank=True, max_length=100, null=True)),
                ('profissao', models.CharField(blank=True, max_length=100, null=True)),
                ('parcelas', models.CharField(blank=True, max_length=100, null=True)),
                ('processo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pedidos.processos')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Servicos.servico')),
            ],
        ),
        migrations.CreateModel(
            name='GarantiaVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_veiculo', models.CharField(blank=True, max_length=100, null=True)),
                ('placa_veiculo', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('ano_modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('ano_fabricacao', models.CharField(blank=True, max_length=100, null=True)),
                ('versao', models.CharField(blank=True, max_length=100, null=True)),
                ('combustivel', models.CharField(blank=True, max_length=100, null=True)),
                ('cambio', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_financiamento', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_entrada', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_do_licenciamento', models.CharField(blank=True, max_length=100, null=True)),
                ('emprestimo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='garantia_veiculo', to='Pedidos.emprestimosemgeral')),
            ],
        ),
        migrations.CreateModel(
            name='GarantiaImoveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_imovel', models.CharField(blank=True, max_length=100, null=True)),
                ('localizacao_estado', models.CharField(blank=True, max_length=100, null=True)),
                ('situacao_imovel', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_imovel', models.CharField(blank=True, max_length=100, null=True)),
                ('compor_renda', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_financiamento', models.CharField(blank=True, max_length=100, null=True)),
                ('qtd_parcelas', models.CharField(blank=True, max_length=100, null=True)),
                ('amortizacao', models.CharField(blank=True, max_length=100, null=True)),
                ('despesas_extra', models.CharField(blank=True, max_length=100, null=True)),
                ('emprestimo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='garantia_imoveis', to='Pedidos.emprestimosemgeral')),
            ],
        ),
        migrations.CreateModel(
            name='EmprestimoEmpresarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade_empresarial', models.CharField(blank=True, max_length=100, null=True)),
                ('faturamento', models.CharField(blank=True, max_length=100, null=True)),
                ('destino_recurso', models.CharField(blank=True, max_length=100, null=True)),
                ('garantia', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_emprestimo', models.CharField(blank=True, max_length=100, null=True)),
                ('emprestimo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresarial', to='Pedidos.emprestimosemgeral')),
            ],
        ),
    ]
