# Generated by Django 4.2.3 on 2024-01-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0081_emprestimoempresarial_processo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garantiaveiculo',
            old_name='estado_do_licenciamento',
            new_name='banco',
        ),
        migrations.RenameField(
            model_name='garantiaveiculo',
            old_name='placa_veiculo',
            new_name='entrada',
        ),
        migrations.RenameField(
            model_name='garantiaveiculo',
            old_name='valor_entrada',
            new_name='estado_licenciamento',
        ),
        migrations.RenameField(
            model_name='garantiaveiculo',
            old_name='valor_financiamento',
            new_name='placa',
        ),
        migrations.AddField(
            model_name='garantiaveiculo',
            name='possui_carroceria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='garantiaveiculo',
            name='prazo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='garantiaveiculo',
            name='valor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
