# Generated by Django 4.2.3 on 2024-01-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0082_rename_estado_do_licenciamento_garantiaveiculo_banco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimosemgeral',
            name='valor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
