# Generated by Django 4.2.3 on 2024-01-04 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0083_emprestimosemgeral_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultoriaContasbil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Contabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DadosBancariosclients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_banco', models.CharField(blank=True, max_length=100, null=True)),
                ('agencia', models.CharField(blank=True, max_length=100, null=True)),
                ('conta', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_conta', models.CharField(blank=True, max_length=100, null=True)),
                ('processo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pedidos.processos')),
            ],
        ),
    ]
