# Generated by Django 4.2.3 on 2024-01-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0084_consultoriacontasbil_contabilidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPessoaisDeTerceiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=15)),
                ('RegistroGeral', models.CharField(max_length=20)),
                ('Data_emissao_rg', models.DateField()),
                ('orgao_emissor_rg', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(max_length=10)),
                ('naturalidade', models.CharField(max_length=100)),
                ('estado_civil', models.CharField(max_length=15)),
                ('cnh', models.CharField(max_length=20)),
                ('filiacao1', models.CharField(max_length=100)),
                ('filiacao2', models.CharField(max_length=100)),
            ],
        ),
    ]
