# Generated by Django 4.2.3 on 2024-01-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0085_dadospessoaisdeterceiros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospessoaisdeterceiros',
            name='Data_emissao_rg',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dadospessoaisdeterceiros',
            name='RegistroGeral',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dadospessoaisdeterceiros',
            name='cnh',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dadospessoaisdeterceiros',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='dadospessoaisdeterceiros',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dadospessoaisdeterceiros',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='dadospessoaisdeterceiros',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='dadospessoaisdeterceiros',
            name='filiacao1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dadospessoaisdeterceiros',
            name='filiacao2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dadospessoaisdeterceiros',
            name='genero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dadospessoaisdeterceiros',
            name='naturalidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dadospessoaisdeterceiros',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dadospessoaisdeterceiros',
            name='orgao_emissor_rg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dadospessoaisdeterceiros',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
