# Generated by Django 4.2.3 on 2024-01-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0087_dadospessoaisdeterceiros_processo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadospessoaisdeterceiros',
            name='agencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dadospessoaisdeterceiros',
            name='conta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dadospessoaisdeterceiros',
            name='nome_banco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dadospessoaisdeterceiros',
            name='tipo_conta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
