# Generated by Django 4.2.3 on 2024-01-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0088_dadospessoaisdeterceiros_agencia_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsultoriaContasbil',
        ),
        migrations.DeleteModel(
            name='Contabilidade',
        ),
        migrations.AddField(
            model_name='clientempresarial',
            name='capital_social',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
