# Generated by Django 4.2.3 on 2024-01-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0090_clientempresarial_ramo_atividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientempresarial',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientempresarial',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
