# Generated by Django 4.2.3 on 2023-08-08 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Afiliados', '0002_rename_cartorio_afiliadosmodel_bairro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('endereco', models.CharField(max_length=200)),
                ('afiliado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Afiliados.afiliadosmodel')),
            ],
        ),
    ]
