# Generated by Django 4.2.3 on 2023-09-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0002_remove_cliente_endereco_remove_cliente_sobrenome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='validation_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
