# Generated by Django 4.2.3 on 2023-09-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0003_cliente_is_validated_cliente_validation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
