# Generated by Django 4.2.3 on 2023-09-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Cliente', '0005_cliente_groups_cliente_is_active_cliente_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='cliente_groups', related_query_name='cliente', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='cliente_user_permissions', related_query_name='cliente', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
