# Generated by Django 4.2.3 on 2023-09-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0007_remove_cliente_groups_remove_cliente_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
