# Generated by Django 4.2.3 on 2023-11-07 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0013_cliente_groups_cliente_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='user_permissions',
        ),
    ]
