# Generated by Django 4.2.3 on 2023-12-09 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0015_cliente_data_emissao_rg_cliente_registrogeral_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='filiacao1',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='filiacao2',
        ),
    ]
