# Generated by Django 4.2.3 on 2023-12-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0016_remove_cliente_filiacao1_remove_cliente_filiacao2'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
