# Generated by Django 4.2.3 on 2023-12-17 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0017_cliente_nome_mae_cliente_nome_pai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='Data_emissao_rg',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='is_validated',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nome_mae',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nome_pai',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='orgao_emissor_rg',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='password',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='profissao',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefone2',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='validation_token',
        ),
        migrations.CreateModel(
            name='ClienteEndereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('complemento', models.CharField(blank=True, max_length=300, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente')),
            ],
        ),
    ]
