# Generated by Django 4.2.3 on 2023-12-17 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cliente', '0018_remove_cliente_data_emissao_rg_remove_cliente_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_como_funcionario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='afiliado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_como_afiliado', to=settings.AUTH_USER_MODEL),
        ),
    ]
