# Generated by Django 4.2.3 on 2023-12-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0019_cliente_funcionario_alter_cliente_afiliado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='acesso',
            field=models.CharField(default='Sem acesso', max_length=15),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
