# Generated by Django 4.2.3 on 2023-12-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0020_alter_cliente_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
    ]
