# Generated by Django 4.2.3 on 2023-12-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0022_alter_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='acesso',
            field=models.CharField(default='Sem acesso', max_length=15),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
