# Generated by Django 4.2.3 on 2023-11-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='Observacoes',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='transacao',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='comprovantesPagamento/'),
        ),
    ]
