# Generated by Django 4.2.3 on 2023-11-01 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_transacao_observacoes_transacao_arquivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='arquivo',
            new_name='comprovante',
        ),
    ]
