# Generated by Django 4.2.3 on 2023-11-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_alter_transacao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='linkpagamento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
