# Generated by Django 4.2.3 on 2023-11-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_transacao_linkpagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente de Pagamento'), ('PAGO', 'Pago'), ('AGUARDANDO', 'Aguardando Confirmação')], default='PENDENTE', max_length=20),
        ),
    ]
