# Generated by Django 4.2.3 on 2023-11-07 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_alter_transacao_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='status',
            new_name='statusPagamento',
        ),
    ]
