# Generated by Django 4.2.3 on 2023-11-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_alter_transacao_statuspagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='statusPagamento',
            field=models.CharField(choices=[('Pendente de Pagamento', 'Pendente de Pagamento'), ('Pago', 'Pago'), ('Aguardando Confirmação', 'Aguardando Confirmação'), ('Link de pagamento não disponível', 'Link de pagamento não disponível'), ('Link de pagamento disponível', 'Link de pagamento disponível'), ('Comprovante não validado', 'Comprovante não validado')], default='Pendente de Pagamento', max_length=100),
        ),
    ]
