# Generated by Django 4.2.3 on 2023-12-01 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servicos', '0007_delete_subservico'),
        ('Pedidos', '0028_rename_cidade_cartorio_processos_formadepagamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financeiro', '0009_alter_transacao_statuspagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransacaoAfiliadoAdministrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FormaDePagamento', models.CharField(blank=True, max_length=100, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('Observacoes', models.CharField(blank=True, max_length=2000, null=True)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantesPagamentoAdm/')),
                ('linkpagamento', models.CharField(blank=True, max_length=200, null=True)),
                ('statusPagamento', models.CharField(choices=[('Pendente de Pagamento', 'Pendente de Pagamento'), ('Pago', 'Pago'), ('Aguardando Confirmação', 'Aguardando Confirmação'), ('Link de pagamento não disponível', 'Link de pagamento não disponível'), ('Link de pagamento disponível', 'Link de pagamento disponível'), ('Comprovante não validado', 'Comprovante não validado')], default='Pendente de Pagamento', max_length=100)),
                ('afiliado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoesAfiliados', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Pedidos.processos')),
                ('servico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Servicos.servico')),
            ],
        ),
    ]
