# Generated by Django 4.2.3 on 2023-12-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0011_transacaoafiliadoadministrador_observacoesafiliado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacaoafiliadoadministrador',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
