# Generated by Django 4.2.3 on 2023-12-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0012_alter_transacaoafiliadoadministrador_preco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='Observacoes',
            new_name='ObservacoesAdm',
        ),
        migrations.AddField(
            model_name='transacao',
            name='ObservacoesFranqueado',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
