# Generated by Django 4.2.3 on 2023-12-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0014_rename_observacoesadm_transacao_observacoesafiliado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacaoafiliadoadministrador',
            old_name='preco',
            new_name='preco_suporte',
        ),
    ]
