# Generated by Django 4.2.3 on 2023-12-15 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financeiro', '0016_alter_transacao_afiliado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='cliente',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'CLIENTE'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_cliente', to=settings.AUTH_USER_MODEL),
        ),
    ]
