# Generated by Django 4.2.3 on 2023-12-15 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financeiro', '0018_alter_transacao_afiliado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='afiliado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes_afiliado', to=settings.AUTH_USER_MODEL),
        ),
    ]
