# Generated by Django 4.2.3 on 2023-07-21 11:44

import Servicos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servico', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subservico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_subservico', models.CharField(max_length=200)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subservicos', to='Servicos.servico')),
            ],
        ),
        migrations.CreateModel(
            name='ModelPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Analise'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], max_length=50)),
                ('mensagem', models.CharField(max_length=500)),
                ('documento', models.FileField(upload_to='documentos/', validators=[Servicos.models.valida_file_extension])),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente')),
                ('sub_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicos.subservico')),
            ],
        ),
    ]
