# Generated by Django 4.2.3 on 2023-08-08 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servico', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subservico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_subservico', models.CharField(max_length=200)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subservicos', to='Servicos.servico')),
            ],
        ),
    ]
