# Generated by Django 4.2.3 on 2023-09-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=200)),
            ],
        ),
    ]
