# Generated by Django 4.2.3 on 2023-07-21 23:01

import Servicos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Analise'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=50),
        ),
        migrations.CreateModel(
            name='ParteEnvolvida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='Servicos.modelpedido')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14)),
                ('indetidade', models.CharField(max_length=20)),
                ('documento', models.FileField(upload_to='documentos_partes/', validators=[Servicos.models.valida_file_extension])),
                ('partes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='Servicos.parteenvolvida')),
            ],
        ),
    ]
