# Generated by Django 4.2.3 on 2023-08-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0002_remove_novocliente_subservico_novocliente_servico'),
        ('Servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Nova Solicitacao', 'Nova Solicitacao'), ('Solicitacao de Consulta', 'Solicitacao de Consulta')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Subservico',
        ),
    ]
