# Generated by Django 4.2.3 on 2023-07-21 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servicos', '0002_alter_modelpedido_status_parteenvolvida_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentoparte',
            old_name='cpf',
            new_name='cpf_envolvido',
        ),
        migrations.RenameField(
            model_name='documentoparte',
            old_name='documento',
            new_name='documento_envolvido',
        ),
        migrations.RenameField(
            model_name='documentoparte',
            old_name='indetidade',
            new_name='indetidade_envolvido',
        ),
        migrations.RenameField(
            model_name='parteenvolvida',
            old_name='nome',
            new_name='nome_envolvido',
        ),
    ]
