# Generated by Django 4.2.3 on 2023-07-21 23:16

import Servicos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicos', '0003_rename_cpf_documentoparte_cpf_envolvido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parteenvolvida',
            name='pedido',
        ),
        migrations.AddField(
            model_name='modelpedido',
            name='cpf_envolvido',
            field=models.CharField(default=0, max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelpedido',
            name='documento_envolvido',
            field=models.FileField(default=0, upload_to='documentos_partes/', validators=[Servicos.models.valida_file_extension]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelpedido',
            name='indetidade_envolvido',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelpedido',
            name='nome_envolvido',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DocumentoParte',
        ),
        migrations.DeleteModel(
            name='ParteEnvolvida',
        ),
    ]
