# Generated by Django 4.2.3 on 2023-07-21 23:19

import Servicos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicos', '0004_remove_parteenvolvida_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpedido',
            name='cpf_envolvido',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='modelpedido',
            name='documento_envolvido',
            field=models.FileField(blank=True, null=True, upload_to='documentos_partes/', validators=[Servicos.models.valida_file_extension]),
        ),
        migrations.AlterField(
            model_name='modelpedido',
            name='indetidade_envolvido',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modelpedido',
            name='nome_envolvido',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
