# Generated by Django 4.2.3 on 2023-09-30 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servicos', '0005_remove_servico_nome_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subservico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_subservico', models.CharField(max_length=200)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subservicos', to='Servicos.servico')),
            ],
        ),
    ]
