# Generated by Django 4.2.3 on 2023-09-30 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servicos', '0006_subservico'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subservico',
        ),
    ]
