# Generated by Django 4.2.3 on 2023-07-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AfiliadosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('Cnpj', models.CharField(max_length=14, unique=True)),
                ('endereco', models.CharField(max_length=200)),
                ('cartorio', models.CharField(max_length=200)),
            ],
        ),
    ]
