# Generated by Django 4.2.3 on 2023-08-26 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Afiliados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afiliadosmodel',
            name='senha',
        ),
    ]
