# Generated by Django 4.2.3 on 2023-08-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Afiliados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='afiliadosmodel',
            old_name='cartorio',
            new_name='bairro',
        ),
        migrations.RenameField(
            model_name='afiliadosmodel',
            old_name='Cnpj',
            new_name='cnpj',
        ),
        migrations.RenameField(
            model_name='afiliadosmodel',
            old_name='sobrenome',
            new_name='razao_social',
        ),
        migrations.AddField(
            model_name='afiliadosmodel',
            name='cep',
            field=models.CharField(default=0, max_length=9, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='afiliadosmodel',
            name='cidade',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='afiliadosmodel',
            name='estado',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
