# Generated by Django 4.2.3 on 2023-08-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Afiliados', '0002_remove_afiliadosmodel_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliadosmodel',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
