# Generated by Django 4.2.3 on 2023-11-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Afiliados', '0005_alter_afiliadosmodel_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliadosmodel',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='afiliado_groups', related_query_name='afiliado', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='afiliadosmodel',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='afiliado_user_permissions', related_query_name='afiliado', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='afiliadosmodel',
            name='user_type',
            field=models.CharField(choices=[('AFILIADO', 'Afiliado'), ('ADMIN', 'Administrador'), ('FUNC', 'Funcionario')], default='AFILIADO', max_length=10),
        ),
    ]
