# Generated by Django 4.2.3 on 2023-11-09 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Afiliados', '0006_alter_afiliadosmodel_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliadosmodel',
            name='afiliado_relacionado',
            field=models.ForeignKey(blank=True, help_text='Afiliado ao qual o funcionário está associado', limit_choices_to={'user_type': 'AFILIADO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='afiliadosmodel',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='afiliadosmodel',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
