# Generated by Django 4.2.3 on 2023-11-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Afiliados', '0007_afiliadosmodel_afiliado_relacionado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliadosmodel',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
