# Generated by Django 4.2.3 on 2023-11-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Afiliados', '0008_afiliadosmodel_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliadosmodel',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='afiliadosmodel',
            name='razao_social',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
