# Generated by Django 4.2.3 on 2023-12-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Afiliados', '0009_alter_afiliadosmodel_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliadosmodel',
            name='Data_emissao_rg',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afiliadosmodel',
            name='RegistroGeral',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='afiliadosmodel',
            name='cnh',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='afiliadosmodel',
            name='complemento',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='afiliadosmodel',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afiliadosmodel',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viuvo', 'Viúvo')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='afiliadosmodel',
            name='genero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='afiliadosmodel',
            name='logradouro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='afiliadosmodel',
            name='naturalidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='afiliadosmodel',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='afiliadosmodel',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='afiliadosmodel',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afiliadosmodel',
            name='orgao_emissor_rg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='afiliadosmodel',
            name='profissao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='afiliadosmodel',
            name='telefone2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='afiliadosmodel',
            name='user_type',
            field=models.CharField(choices=[('AFILIADO', 'Afiliado'), ('ADMIN', 'Administrador'), ('FUNC', 'Funcionario'), ('CLIENTE', 'Cliente')], max_length=100),
        ),
    ]
