# Generated by Django 4.2.3 on 2023-12-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Afiliados', '0010_afiliadosmodel_data_emissao_rg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliadosmodel',
            name='bairro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='afiliadosmodel',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='afiliadosmodel',
            name='cidade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='afiliadosmodel',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='afiliadosmodel',
            name='estado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
