# Generated by Django 4.2.3 on 2023-12-14 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Afiliados', '0011_alter_afiliadosmodel_bairro_alter_afiliadosmodel_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliadosmodel',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afiliado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
