# Generated by Django 4.2.3 on 2023-12-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Afiliados', '0012_alter_afiliadosmodel_telefone_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliadosmodel',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='afiliadosmodel',
            name='validation_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
